### ISSUE TITLE
[Hardhat] Hardhat plugin phase 2

### ISSUE THREAD

**Issue by acuarica** [hashgraph/hedera-forking#104]
This is the initial set of tasks to continue improving the Hardhat plugin.

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-forking/issues/78
- [ ] https://github.com/hashgraph/hedera-forking/issues/79
- [ ] https://github.com/hashgraph/hedera-forking/issues/80
- [ ] https://github.com/hashgraph/hedera-forking/issues/111
- [ ] https://github.com/hashgraph/hedera-forking/issues/126
```
