### ISSUE TITLE
Remove `out/HtsSystemContract.sol/HtsSystemContract.json` from version control

### ISSUE THREAD

**Issue by acuarica** [hashgraph/hedera-forking#122]
The `out/HtsSystemContract.sol/HtsSystemContract.json` file contains the compilation output of `HtsSystemContract.sol`. This file is currently included in the repo. The initial idea of having this file in the repo was to allow users to consume JS packages directly from GitHub, _i.e._, _without_ a build step. Given that this is not the case (we decided to publish to npm), we can remove this file from git.

In order to run JS `scripts`, _e.g._, `npm run type-check` or JS unit tests, _e.g._, `npm run test --workspace=@hts-forking`, we need to compile the contract first

```console
$ forge build
```

```[tasklist]
### Tasks
- [x] Remove this file from repo
- [x] Fix CI `test` workflow that executes JS related scripts
- [x] Remove related entry in `.gitignore` given won't be needed anymore
```
