### ISSUE TITLE
Community forking issues

### ISSUE THREAD

**Issue by acuarica** [hashgraph/hedera-forking#146]
This epic consolidates issues related to forking opened by the community in other repos before we had a solution in the making.

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/702
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/718
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/863
- [ ] https://github.com/hiero-ledger/hiero-json-rpc-relay/issues/2161
- [ ] https://github.com/hiero-ledger/hiero-json-rpc-relay/issues/633
- [ ] https://github.com/hiero-ledger/hiero-json-rpc-relay/issues/477
```

The following is not related to forking, but it's related to "Mock" (emulate) HTS in the Smart Contracts repo.

- https://github.com/hashgraph/hedera-smart-contracts/issues/477
- https://github.com/hashgraph/hedera-smart-contracts/issues/479

**Comment by Nana-EC** [comment]
@acuarica do we intend to verify these issues this sprint? If not please move back to backlog

**Comment by acuarica** [comment]
Yes, I'd like to address them in this sprint.

**Comment by acuarica** [comment]
All items marked as completed, closing this.
