### ISSUE TITLE
[Hardhat] Hardhat plugin to support HTS in a forked network

### ISSUE THREAD

**Issue by acuarica** [hashgraph/hedera-forking#70]
Create a Hardhat plugin to support usage of HTS in a forked network.

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-forking/issues/44
- [ ] https://github.com/hashgraph/hedera-forking/issues/51
- [ ] https://github.com/hashgraph/hedera-forking/issues/55
- [ ] https://github.com/hashgraph/hedera-forking/issues/57
- [ ] https://github.com/hashgraph/hedera-forking/issues/56
- [ ] https://github.com/hashgraph/hedera-forking/issues/68
- [ ] https://github.com/hashgraph/hedera-forking/issues/73
- [ ] https://github.com/hashgraph/hedera-forking/issues/54
- [ ] https://github.com/hashgraph/hedera-forking/issues/77
- [ ] https://github.com/hashgraph/hedera-forking/issues/45
- [ ] https://github.com/hashgraph/hedera-forking/issues/75
- [ ] https://github.com/hashgraph/hedera-forking/issues/100
- [ ] https://github.com/hashgraph/hedera-forking/issues/179
```

**Comment by acuarica** [comment]
Closing as the items included here were completed.
