### ISSUE TITLE
[Core] Implement HIP-719 for fungible tokens

### ISSUE THREAD

**Issue by acuarica** [hashgraph/hedera-forking#82]
The [HIP-719](https://hips.hedera.com/hip/hip-719) specifies the `associate`, `dissociate` and `isAssociated` methods on HTS tokens. It's an extension of the ERC20 interface. These methods are important when mimicking HTS behavior in transfer tokens transactions.

Implement these methods in the `HtsSystemContract`. Fetching the state for both Hardhat and Foundry are to be done in following PRs.

```[tasklist]
### Tasks
- [x] Include [`IHRC719.sol`](https://github.com/hashgraph/hedera-smart-contracts/blob/6d4bb129089770f96c3ca48dd043d68295558a2d/contracts/system-contracts/hedera-token-service/IHRC719.sol) interface in `src/`.
- [x] Extend the `__redirectForToken` method to support the new methods mentioned above. Given the usage of `associate` and `dissociate`, the storage emulation should be similar to that of `balanceOf`.
- [x] Add unit tests for `associate`, `dissociate`, `isAssociate`
```
