### ISSUE TITLE
[Foundry] Add support for Hedera FT and NFT in Foundry

### ISSUE THREAD

**Issue by se7enarianelabs** [hashgraph/hedera-forking#94]
**Description**
This Epic extends the current HTS  Fungible Token (FT) Foundry Support Proof of Concept (PoC)  to provide a complete, production-ready implementation. The initial PoC enabled basic IERC20 functionality, and this Epic will address remaining functionalities and improvements to create a fully integrated and scalable solution for Hedera Token Service (HTS) within the Foundry environment.

Goals:
- Complete the integration of Hedera Fungible and Non-Fungible Tokens in Foundry.
- Design a robust architecture to support HTS in Foundry.
- Enable critical operations such as mint, burn, association, and allowance management with Hedera's FT.

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-forking/issues/95
- [ ] https://github.com/hashgraph/hedera-forking/issues/97
- [ ] https://github.com/hashgraph/hedera-forking/issues/98
- [ ] https://github.com/hashgraph/hedera-forking/issues/78
- [ ] https://github.com/hashgraph/hedera-forking/issues/102
- [ ] https://github.com/hashgraph/hedera-forking/issues/48
- [ ] https://github.com/hashgraph/hedera-forking/issues/125
```

**Comment by acuarica** [comment]
Epic items completed.
